services:
  fe:
    build:
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000/" ]
      interval: 5s
      timeout: 20s
      retries: 10
