services:
  fe:
    build:
      dockerfile: Dockerfile
    pull_policy: build
    restart: always
    environment:
      COOLIFY_URL: 'https://something.asdss.de:8080'
      COOLIFY_FQDN: 'https://something.asdss.de:8080'
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://127.0.0.1:80/" ]
      interval: 5s
      timeout: 20s
      retries: 10
