services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NPM_TOKEN: ${NPM_TOKEN:?NPM_TOKEN not set}
    ports:
      - "3000"
    environment:
      - PORT=3000
      - DB_CONNECTION=postgres
      - TEST=${TEST}
